#!/usr/bin/env node

const fs = require('fs')

require('../environment.js')

const coingecko = require('../server/lib/coingecko')

;(async function() {
  const exchangesList = await coingecko.request(
    '/exchanges/list'
  )

  fs.writeFileSync(
    './shared/coingeckoExchangeList.js',
    `module.exports = ${JSON.stringify(exchangesList)}`
  )
})()
