#!/usr/bin/env node

const { server } = require('../server/app')
const env = process.env.NODE_ENV
const port = process.env.PORT
process.title = `Woo Stats PORT=${port}`

// Start server
server.listen(port, '0.0.0.0', function() {
  console.log(`server started at port:${port} in ${env} mode`) // eslint-disable-line no-console
})
